version: '3'
services:
  video-streaming:
    image: nutthanich.azurecr.io/video-streaming
    build:
      context: ./video-streaming-server
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4000:80"
    environment:
      - PORT=80
    restart: "no"
